prompt Importing table testUser_jdbc.Answers...
set feedback off
set define off
insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15565', '1', '(1)床上用品', '1', null, '0', '0', '0', '4851', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15566', '2', '(2)被子', '2', null, '0', '0', '0', '4851', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15567', '3', '(3)枕头', '3', null, '0', '0', '0', '4851', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15568', '4', '(4)毛巾', '4', null, '0', '0', '0', '4851', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15569', '5', '(5)毯子', '5', null, '0', '0', '0', '4851', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15570', '6', '(6)窗帘', '6', null, '0', '0', '0', '4851', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15571', '7', '(7)被类', '7', null, '0', '0', '0', '4851', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15572', '1', '(1)自用旧产品更新', '1', null, '0', '0', '0', '4852', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15573', '2', '(2)换季添置', '2', null, '0', '0', '0', '4852', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15574', '3', '(3)打折促销', '3', null, '0', '0', '0', '4852', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15575', '4', '(4)新居装修', '4', null, '0', '0', '0', '4852', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15576', '5', '(5)婚庆', '5', null, '0', '0', '0', '4852', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15577', '6', '(6)送礼', '6', null, '0', '0', '0', '4852', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15578', '1', '(1)1-2年', '1', null, '0', '0', '0', '4853', '0', '4', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15579', '2', '(2)2—3年', '2', null, '0', '0', '0', '4853', '0', '4', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15580', '3', '(3)3—5年', '3', null, '0', '0', '0', '4853', '0', '4', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15581', '4', '(4)5年以上', '4', null, '0', '0', '0', '4853', '0', '4', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15582', '5', '(5)不确定', '5', null, '0', '0', '0', '4853', '0', '4', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15583', '1', '(1)换季时', '1', null, '0', '0', '0', '4854', '0', '5', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15584', '2', '(2)1—2年', '2', null, '0', '0', '0', '4854', '0', '5', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15585', '3', '(3)2—3年', '3', null, '0', '0', '0', '4854', '0', '5', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15586', '4', '(4)3—5年', '4', null, '0', '0', '0', '4854', '0', '5', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15587', '5', '(5)5年以上', '5', null, '0', '0', '0', '4854', '0', '5', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15588', '1', '(1) 1个月', '1', null, '0', '0', '0', '4855', '0', '6', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15589', '2', '(2)1季度', '2', null, '0', '0', '0', '4855', '0', '6', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15590', '3', '(3)半年', '3', null, '0', '0', '0', '4855', '0', '6', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15591', '4', '(4)一年', '4', null, '0', '0', '0', '4855', '0', '6', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15592', '5', '(5)不确定', '5', null, '0', '0', '0', '4855', '0', '6', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15593', '1', '(1)不喜欢就换', '1', null, '0', '0', '0', '4856', '0', '7', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15594', '2', '(2)新居装修时更换', '2', null, '0', '0', '0', '4856', '0', '7', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15595', '3', '(3)1-5年内', '3', null, '0', '0', '0', '4856', '0', '7', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15596', '4', '(4)5年以上', '4', null, '0', '0', '0', '4856', '0', '7', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15597', '1', '(1)500元以下', '1', null, '0', '0', '0', '4857', '0', '8', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15598', '2', '(2)501-1500元', '2', null, '0', '0', '0', '4857', '0', '8', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15599', '3', '(3)1501-3500元', '3', null, '0', '0', '0', '4857', '0', '8', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15600', '4', '(4)3501—6000元', '4', null, '0', '0', '0', '4857', '0', '8', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15601', '5', '(5)6000—1万元', '5', null, '0', '0', '0', '4857', '0', '8', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15602', '6', '(6)1万元以上', '6', null, '0', '0', '0', '4857', '0', '8', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15603', '1', '(1)200元以下', '1', null, '0', '0', '0', '4858', '0', '9', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15604', '2', '(2)201-500元', '2', null, '0', '0', '0', '4858', '0', '9', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15605', '3', '(3)501-1000元', '3', null, '0', '0', '0', '4858', '0', '9', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15606', '4', '(4)1001—2000元', '4', null, '0', '0', '0', '4858', '0', '9', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15607', '5', '(5)2001-4000元', '5', null, '0', '0', '0', '4858', '0', '9', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15608', '6', '(6)4000元以上', '6', null, '0', '0', '-1', '4858', '1', '9', null, '0', '300', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15609', '1', '(1)50元/米以下', '1', null, '0', '0', '0', '4859', '0', '10', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15610', '2', '(2)51-100/米', '2', null, '0', '0', '0', '4859', '0', '10', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15611', '3', '(3)101-200/米', '3', null, '0', '0', '0', '4859', '0', '10', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15612', '4', '(4)200—500 /米', '4', null, '0', '0', '0', '4859', '0', '10', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15613', '5', '(5)500元/米以上', '5', null, '0', '0', '0', '4859', '0', '10', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15614', '1', '(1)10元/条以下', '1', null, '0', '0', '0', '4860', '0', '11', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15615', '2', '(2)11-20元/条', '2', null, '0', '0', '0', '4860', '0', '11', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15616', '3', '(3)21-40元/条', '3', null, '0', '0', '0', '4860', '0', '11', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15617', '4', '(4)41—60元/条', '4', null, '0', '0', '0', '4860', '0', '11', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15618', '5', '(5)60元/条以上', '5', null, '0', '0', '0', '4860', '0', '11', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15619', '1', '(1)百货商场', '1', null, '0', '0', '0', '4861', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15620', '2', '(2)专卖店', '2', null, '0', '0', '0', '4861', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15621', '3', '(3)超市', '3', null, '0', '0', '0', '4861', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15622', '4', '(4)专业市场', '4', null, '0', '0', '0', '4861', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15623', '5', '(5)网上购买', '5', null, '0', '0', '0', '4861', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15624', '1', '(1)百货商场', '1', null, '0', '0', '0', '4862', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15625', '2', '(2)专卖店', '2', null, '0', '0', '0', '4862', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15626', '3', '(3)超市', '3', null, '0', '0', '0', '4862', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15627', '4', '(4)批发市场', '4', null, '0', '0', '0', '4862', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15628', '5', '(5)网上购买', '5', null, '0', '0', '0', '4862', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15629', '1', '(1)布艺专业市场', '1', null, '0', '0', '0', '4863', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15630', '2', '(2)建材城', '2', null, '0', '0', '0', '4863', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15631', '3', '(3)专卖店', '3', null, '0', '0', '0', '4863', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15632', '4', '(4)家居店', '4', null, '0', '0', '0', '4863', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15633', '5', '(5)网上购买', '5', null, '0', '0', '0', '4863', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15634', '1', '(1)单件', '1', null, '0', '0', '0', '4864', '0', '15', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15635', '2', '(2)三件套', '2', null, '0', '0', '0', '4864', '0', '15', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15636', '3', '(3)四件套', '3', null, '0', '0', '0', '4864', '0', '15', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15637', '4', '(4)六件套', '4', null, '0', '0', '0', '4864', '0', '15', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15638', '5', '(5)多件套', '5', null, '0', '0', '0', '4864', '0', '15', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15639', '1', '品牌', '1', null, '0', '0', '0', '4865', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15640', '2', '面料材质', '2', null, '0', '0', '0', '4865', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15641', '3', '价格', '3', null, '0', '0', '0', '4865', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15642', '4', '安全性', '4', null, '0', '0', '0', '4865', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15643', '5', '时尚性', '5', null, '0', '0', '0', '4865', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15644', '6', '耐用性', '6', null, '0', '0', '0', '4865', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15645', '7', '功能性', '7', null, '0', '0', '0', '4865', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15646', '1', '第1重要', '8', null, '0', '0', '0', '4865', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15647', '2', '第2重要', '9', null, '0', '0', '0', '4865', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15648', '3', '第3重要', '10', null, '0', '0', '0', '4865', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15649', '4', '最不重要', '11', null, '0', '0', '0', '4865', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15650', '1', '品牌', '1', null, '0', '0', '0', '4866', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15651', '2', '面料材质', '2', null, '0', '0', '0', '4866', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15652', '3', '价格', '3', null, '0', '0', '0', '4866', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15653', '4', '功能性', '4', null, '0', '0', '0', '4866', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15654', '5', '填充物', '5', null, '0', '0', '0', '4866', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15655', '6', '制作工艺', '6', null, '0', '0', '0', '4866', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15656', '1', '第1重要', '7', null, '0', '0', '0', '4866', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15657', '2', '第2重要', '8', null, '0', '0', '0', '4866', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15658', '3', '第3重要', '9', null, '0', '0', '0', '4866', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15659', '4', '最不重要', '10', null, '0', '0', '0', '4866', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15660', '1', '品牌或销售商价格', '1', null, '0', '0', '0', '4867', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15661', '2', '材质', '2', null, '0', '0', '0', '4867', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15662', '3', '价格', '3', null, '0', '0', '0', '4867', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15663', '4', '款式设计', '4', null, '0', '0', '0', '4867', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15664', '5', '色彩/图案', '5', null, '0', '0', '0', '4867', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15665', '6', '功能性（防紫外线、遮光、阻燃、防噪音、防尘）', '6', null, '0', '0', '0', '4867', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15666', '7', '售前售后服务', '7', null, '0', '0', '0', '4867', '0', '0', null, '-1', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15667', '1', '第1重要', '8', null, '0', '0', '0', '4867', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15668', '2', '第2重要', '9', null, '0', '0', '0', '4867', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15669', '3', '第3重要', '10', null, '0', '0', '0', '4867', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15670', '4', '最不重要', '11', null, '0', '0', '0', '4867', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15671', '1', '(1)棉被', '1', null, '0', '0', '0', '4868', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15672', '2', '(2)羽绒被', '2', null, '0', '0', '0', '4868', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15673', '3', '(3)蚕丝被', '3', null, '0', '0', '0', '4868', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15674', '4', '(4)羊毛被', '4', null, '0', '0', '0', '4868', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15675', '5', '(5)化纤被（中空棉）', '5', null, '0', '0', '0', '4868', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15676', '6', '其它，请注明', '6', null, '0', '0', '-1', '4868', '1', '0', null, '0', '100', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15677', '1', '(1)网上购买', '1', null, '0', '0', '0', '4869', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15678', '2', '(2)电视购物', '2', null, '0', '0', '0', '4869', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15679', '3', '(3)社区销售', '3', null, '0', '0', '0', '4869', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15680', '4', '(4)不清楚', '4', null, '0', '-1', '0', '4869', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15681', '1', '(1)涨价10%以内', '1', null, '0', '0', '0', '4870', '0', '22', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15682', '2', '(2)涨价30%以内', '2', null, '0', '0', '0', '4870', '0', '22', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15683', '3', '(3)涨价50%以内', '3', null, '0', '0', '0', '4870', '0', '22', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15684', '4', '(4)涨价70%以内', '4', null, '0', '0', '0', '4870', '0', '22', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15685', '5', '(5)涨价在一倍以内', '5', null, '0', '0', '0', '4870', '0', '22', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15686', '6', '(6)涨价在一倍以上', '6', null, '0', '0', '0', '4870', '0', '22', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15687', '1', '男', '1', null, '0', '0', '0', '4872', '0', '24', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15688', '2', '女', '2', null, '0', '0', '0', '4872', '0', '24', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15689', '1', '(1)24岁以下', '1', null, '0', '0', '0', '4873', '0', '25', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15690', '2', '(2)25-34岁', '2', null, '0', '0', '0', '4873', '0', '25', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15691', '3', '(3)35-44岁', '3', null, '0', '0', '0', '4873', '0', '25', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15692', '4', '(4)45-54', '4', null, '0', '0', '0', '4873', '0', '25', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15693', '5', '(5)55-64', '5', null, '0', '0', '0', '4873', '0', '25', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15694', '6', '(6)65岁及以上', '6', null, '0', '0', '0', '4873', '0', '25', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15695', '1', '已结婚', '1', null, '0', '0', '0', '4874', '0', '26', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15696', '2', '未结婚', '2', null, '0', '0', '0', '4874', '0', '26', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15697', '1', '(1)有子女', '1', null, '0', '0', '0', '4875', '0', '27', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15698', '2', '(2)没子女', '2', null, '0', '0', '0', '4875', '0', '27', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15699', '1', '(1)独居', '1', null, '0', '0', '0', '4876', '0', '28', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15700', '2', '(2)与家人同住', '2', null, '0', '0', '0', '4876', '0', '28', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15701', '1', '(1)普通职员', '1', null, '0', '0', '0', '4877', '0', '29', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15702', '2', '(2)中级管理人员', '2', null, '0', '0', '0', '4877', '0', '29', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15703', '3', '(3)高级管理人员', '3', null, '0', '0', '0', '4877', '0', '29', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15704', '4', '(4)企业主', '4', null, '0', '0', '0', '4877', '0', '29', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15705', '5', '(5)公务员', '5', null, '0', '0', '0', '4877', '0', '29', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15706', '6', '(6)教师', '6', null, '0', '0', '0', '4877', '0', '29', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15707', '7', '(7)自由职业', '7', null, '0', '0', '0', '4877', '0', '29', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15708', '8', '(8)其他', '8', null, '0', '0', '-1', '4877', '1', '29', null, '0', '100', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15709', '1', '(1)3500以下', '1', null, '0', '0', '0', '4878', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15710', '2', '(2)3501-5000', '2', null, '0', '0', '0', '4878', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15711', '3', '(3)5001-8000', '3', null, '0', '0', '0', '4878', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15712', '4', '(4)8001-12000', '4', null, '0', '0', '0', '4878', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15713', '5', '(5)1.2万元以上', '5', null, '0', '0', '0', '4878', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15714', '1', '(1)网络', '1', null, '0', '0', '0', '4879', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15715', '2', '(2)报刊、杂志', '2', null, '0', '0', '0', '4879', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15716', '3', '(3)电视', '3', null, '0', '0', '0', '4879', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15717', '4', '(4)广告', '4', null, '0', '0', '0', '4879', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15718', '5', '(5)朋友推荐', '5', null, '0', '0', '0', '4879', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15719', '6', '(6)销售人员介绍', '6', null, '0', '0', '0', '4879', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('15720', '7', '(7)自我体验', '7', null, '0', '0', '0', '4879', '0', '0', null, '0', '0', '0');

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5223', '01', '1.武警/军队', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5224', '02', '2.司法部/检察院/法院', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5225', '03', '3.警察/监狱/消防', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5226', '04', '4.保安公司', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5227', '05', '5.官方机构', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5228', '06', '6.银行/金融/保险/证券', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5229', '07', '7.海关、口岸', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5230', '08', '8.医疗/医院', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5231', '09', '9.交通', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5232', '10', '10.水利', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5233', '11', '11.电力', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5234', '12', '12.工矿企业', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5235', '13', '13.房地产商/物业管理', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5236', '14', '14.酒店/商业/零售', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5237', '15', '15.通讯', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5238', '16', '16.教育/培训/院校', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5239', '17', '17.个人用户', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5240', '18', '18.其它', '0', null, '0', '0', '-1', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5241', '19', '19.制造商', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5242', '20', '20.经销分销商/办事处', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5243', '21', '21.代理商/进出口公司', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5244', '22', '22.行业协会/技防办', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5245', '23', '23.市场调查/工程咨询/安全顾问', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5246', '24', '24.系统集成商/工程商', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5247', '25', '25.科研机构', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5248', '26', '26.工程设计规划', '0', null, '0', '0', '0', '515', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5249', '27', '1.设备管理', '0', null, '0', '0', '0', '516', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5250', '28', '2.工程/维护', '0', null, '0', '0', '0', '516', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5251', '29', '3.企业负责人', '0', null, '0', '0', '0', '516', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5252', '30', '4.法律执行/公共安全', '0', null, '0', '0', '0', '516', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5253', '31', '5.采购部门', '0', null, '0', '0', '0', '516', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5254', '32', '6.安全管理', '0', null, '0', '0', '0', '516', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5255', '33', '7.销售及市场', '0', null, '0', '0', '0', '516', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5256', '34', '8.技术人员/设计人员', '0', null, '0', '0', '0', '516', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5257', '35', '9.媒体和宣传', '0', null, '0', '0', '0', '516', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5258', '36', '10.其它(请注明)', '0', null, '0', '0', '-1', '516', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5259', '37', '1.订购产品', '0', null, '0', '0', '0', '517', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5260', '38', '2.搜集资料', '0', null, '0', '0', '0', '517', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5261', '39', '3.搜集新产品', '0', null, '0', '0', '0', '517', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5262', '40', '4.与供应商及厂家联络', '0', null, '0', '0', '0', '517', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5263', '41', '5.寻求代理、分销商渠道', '0', null, '0', '0', '0', '517', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5264', '42', '6.评估本届博览会以做下届展会的参展计划', '0', null, '0', '0', '0', '517', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5265', '43', '7.其它(请注明)()', '0', null, '0', '0', '-1', '517', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5266', '44', '1.网站信息', '0', null, '0', '0', '0', '518', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5267', '45', '2.杂志广告', '0', null, '0', '0', '0', '518', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5268', '46', '3.行政公文', '0', null, '0', '0', '0', '518', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5269', '47', '4.门票', '0', null, '0', '0', '0', '518', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5270', '48', '5.协会邀请函', '0', null, '0', '0', '0', '518', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5271', '49', '6.短信', '0', null, '0', '0', '0', '518', null, null, null, null, null, null);

insert into testUser_jdbc.Answers (ANSID, ANSDISPLAYNUM, ANSTITLE, ANSNUM, ANSLINK, ANSIMAGEID, ANSREPELOTHERS, ANSINPUTTEXT, QUSID, AVTID, ANSNEXTQUSID, ANSDEFAULTTIP, ANSISHORIZONTAL, ANSMAX, ANSMIN)
values ('5272', '50', '7.主办方的邀请邮件', '0', null, '0', '0', '0', '518', null, null, null, null, null, null);

prompt Done.
